
import { Prompt, Quiz, EaseItResponse, Subject } from './types';

// Mock function for development purposes
// In production, this would connect to Gemini API via Supabase Edge Functions
export const generateSubjectSuggestions = async (
  broadSubject: string
): Promise<Subject[]> => {
  console.log(`Getting subject suggestions for: ${broadSubject}`);
  // In a real app, this would call the Gemini API via a Supabase Edge Function
  
  // Mock response based on common subjects
  const mockSubjects: Record<string, Subject[]> = {
    physics: [
      {
        id: 'quantum-mechanics',
        name: 'Quantum Mechanics',
        description: 'Study of matter and energy at the most fundamental level',
        promptCount: 100
      },
      {
        id: 'astrophysics',
        name: 'Astrophysics',
        description: 'Physics of stars, galaxies and the universe',
        promptCount: 100
      },
      {
        id: 'relativity',
        name: 'Theory of Relativity',
        description: 'Einstein\'s revolutionary framework of space and time',
        promptCount: 100
      }
    ],
    computer: [
      {
        id: 'machine-learning',
        name: 'Machine Learning',
        description: 'Systems that can learn from data',
        promptCount: 100
      },
      {
        id: 'web-development',
        name: 'Web Development',
        description: 'Building applications for the internet',
        promptCount: 100
      },
      {
        id: 'cybersecurity',
        name: 'Cybersecurity',
        description: 'Protecting systems from digital attacks',
        promptCount: 100
      }
    ],
    biology: [
      {
        id: 'genetics',
        name: 'Genetics',
        description: 'Study of genes and heredity',
        promptCount: 100
      },
      {
        id: 'ecology',
        name: 'Ecology',
        description: 'Relationships between organisms and environment',
        promptCount: 100
      },
      {
        id: 'neuroscience',
        name: 'Neuroscience',
        description: 'Study of the nervous system and brain',
        promptCount: 100
      }
    ],
    // Default response for any other input
    default: [
      {
        id: 'introduction',
        name: `Introduction to ${broadSubject}`,
        description: `Foundational principles of ${broadSubject}`,
        promptCount: 100
      },
      {
        id: 'advanced',
        name: `Advanced ${broadSubject}`,
        description: `Complex topics in ${broadSubject}`,
        promptCount: 100
      },
      {
        id: 'applications',
        name: `Applied ${broadSubject}`,
        description: `Practical applications of ${broadSubject} in the real world`,
        promptCount: 100
      }
    ]
  };

  // Normalize input to lowercase and find closest match
  const normalizedInput = broadSubject.toLowerCase();
  let matchedKey = 'default';
  
  for (const key of Object.keys(mockSubjects)) {
    if (normalizedInput.includes(key)) {
      matchedKey = key;
      break;
    }
  }

  // Add a small delay to simulate API call
  await new Promise(resolve => setTimeout(resolve, 800));
  
  return mockSubjects[matchedKey as keyof typeof mockSubjects] || mockSubjects.default;
};

export const getPrompt = async (
  subjectId: string,
  promptNumber: number
): Promise<Prompt> => {
  console.log(`Getting prompt ${promptNumber} for subject ${subjectId}`);
  // In a real app, this would call the Gemini API via a Supabase Edge Function
  
  // Add a small delay to simulate API call
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  // Mock response
  return {
    number: promptNumber,
    title: `Understanding ${subjectId.split('-').join(' ')} - Part ${promptNumber}`,
    conceptExplanation: `This is where a detailed explanation of the concept for prompt ${promptNumber} would appear. The content would be generated by Gemini API and would include relevant theoretical foundations, key principles, and important definitions related to ${subjectId.split('-').join(' ')}.`,
    realWorldExamples: `Here are some practical examples of how this concept applies in real-world scenarios:

1. Example One: A detailed description of how this concept manifests in everyday life or professional settings.
2. Example Two: Another scenario showing the practical application of this theoretical knowledge.
3. Example Three: A final demonstration of how understanding this concept can help solve real problems.`,
    caseStudies: promptNumber % 3 === 0 ? `Case Study: An in-depth examination of how this concept was applied to solve a specific problem or advance knowledge in the field.` : undefined,
    task: `Your task: Take 5 minutes to reflect on how you might apply this concept in your own context, and write down at least three potential applications.`,
    diagramCode: promptNumber % 4 === 0 ? 
      `graph TD
        A[Concept Introduction] --> B[Key Principles]
        B --> C[Application Methods]
        B --> D[Common Misconceptions]
        C --> E[Real-world Application]
        D --> F[Corrected Understanding]
        E --> G[Mastery]
        F --> G` : undefined
  };
};

export const getQuiz = async (
  subjectId: string,
  promptRange: [number, number]
): Promise<Quiz> => {
  console.log(`Getting quiz for subject ${subjectId} covering prompts ${promptRange[0]}-${promptRange[1]}`);
  
  // Add a small delay to simulate API call
  await new Promise(resolve => setTimeout(resolve, 1200));
  
  // Mock response
  return {
    promptNumber: promptRange[1],
    questions: [
      {
        question: `What is the main principle behind ${subjectId.split('-').join(' ')} as discussed in the recent prompts?`,
        options: [
          'A potential incorrect answer',
          'The correct answer would be here',
          'Another incorrect option',
          'A final distractor option'
        ],
        correctAnswerIndex: 1,
        type: 'multiple-choice'
      },
      {
        question: `How would you apply the concept from prompt ${promptRange[0] + 2} in a real-world scenario?`,
        type: 'short-answer'
      },
      {
        question: `Which of the following is NOT an example of the concept explained in prompt ${promptRange[0] + 5}?`,
        options: [
          'This would be a correct example',
          'This would be a correct example also',
          'This would be the INCORRECT example (the answer)',
          'This would be another correct example'
        ],
        correctAnswerIndex: 2,
        type: 'multiple-choice'
      }
    ]
  };
};

export const getEaseItExplanation = async (
  prompt: Prompt
): Promise<EaseItResponse> => {
  console.log(`Getting simplified explanation for prompt ${prompt.number}`);
  
  // Add a small delay to simulate API call
  await new Promise(resolve => setTimeout(resolve, 800));
  
  // Mock response
  return {
    analogy: `Imagine this concept is like riding a bicycle. When you first learn, you focus intensely on balance (similar to how in ${prompt.title.split(' - ')[0]}, you need to understand the fundamental principle first). Once you master balance, you can start thinking about direction and speed (the more advanced applications).`,
    simplifiedExplanation: `In simple terms: ${prompt.conceptExplanation.split('.')[0]}. The key thing to remember is that this is all about how things relate to each other and the patterns they form.`
  };
};
