// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sawwpulwxtxrwpnyyucy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhd3dwdWx3eHR4cndwbnl5dWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDcyOTksImV4cCI6MjA2MTUyMzI5OX0.Gc1z4n-2LuvQw0nSMnds1QnfYHzPscxGs9EMoXkHqbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);